### ISSUE TITLE
Performance issue many users

### ISSUE THREAD

**Issue by NathalieSpierings** [TypecastException/AspNetIdentity2GroupPermissions#18]
Situation:
I have an application with let's say 1500 users.
I have 5 groups
I have 80 roles.
The roles are spread over the 5 groups.
When i enable or disable a role for a group, all roles for the group users changes. 
This takes for ever to loop true all users, remove all roles and add all new roles.

**Comment by xivSolutions** [comment]
HI!
 Indeed, this project is not a formally supported attempt to implement permissions management at scale. In fact, it was more of a hack I personally needed to get in place where I worked at the time, and I just happened to write a blog post about it. 

I strongly recommend seeking a better alternative for the size user base you are using. 

This was more of a way to learn about Identity than anything else, and you'll see in the post I wrote I acknowledge the notion that this is not really a general use, production-ready library. 

That said, solutions for performance issues are also usually good learning moments, so if you want to shoot a PR, I'm sure the fix would be instructive for others!
